### PR TITLE
migrate go to provided.al2023 and update localstack to docker compose

### PR DESCRIPTION
**Pull request by ncostamagna**
Hi @wimspaargaren, thanks for sharing your project

I carried out some changes to run the project locally

- migrate go1.x runner to provided.al2023
- replace docker to docker compose (adding SERVICES and volume)
- rename the account number format in the role name

### CODE REVIEW

**Comment by wimspaargaren** [comment]
Hi @ncostamagna , thanks for your contribution! Looks good to me :) One small thing: Could you fix the new lines in the `docker-compose.yml` and the `.gitignore`?

**Comment by ncostamagna** [comment]
Hi @wimspaargaren , how are you? :)
Yes, of course, I've just made the changes in the PR, adding the new line in the docker-file and the .gitignore files

**Review by nnblaze — APPROVED** [review]

**Review by wimspaargaren — APPROVED** [review]
Hey sorry for the slow response, my daughter was born in the mean time 😄 Going to merge this one!

**Comment by ncostamagna** [comment]
That's wonderful! I'm so happy for you! Congratulations @wimspaargaren ! 😃😃

**Comment by wimspaargaren** [comment]
Thx 😄 added a small fix on top of your work btw: https://github.com/wimspaargaren/go-lambda-localstack-example/commit/c6e58efbd4640b46d5a2c9c269caa8893fb8445b

**Pull request merged**
